create table if not exists readings (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  mq_raw numeric not null,
  mq_scaled numeric not null,
  uv_raw numeric not null,
  uv_voltage numeric not null,
  uv_index numeric not null,
  voltage numeric not null default 5.0,
  air_level text not null
);

create index if not exists readings_created_at_idx
on readings (created_at desc);
